### ISSUE TITLE
error: conflicting declaration ‘typedef struct _GSocket GSocket’

### ISSUE THREAD

**Issue by conradwt** [etexteditor/e#67]
Hi, The e-texteditor fails to build on Ubuntu 9.10.  Thus, I'm getting the following error message:

$ make DEBUG=1
[CC] BundleItemEditorCtrl.cpp
In file included from /usr/include/glib-2.0/gio/gio.h:28,
                 from /usr/include/gtk-2.0/gdk/gdkapplaunchcontext.h:30,
                 from /usr/include/gtk-2.0/gdk/gdk.h:32,
                 from /usr/include/gtk-2.0/gtk/gtk.h:32,
                 from key_hook.h:13,
                 from EditorCtrl.h:29,
                 from BundleItemEditorCtrl.h:4,
                 from BundleItemEditorCtrl.cpp:1:
/usr/include/glib-2.0/gio/giotypes.h:120: error: conflicting declaration ‘typedef struct _GSocket GSocket’
/home/conradwt/c.dir/projects/e/external/out.debug/include/wx-2.8/wx/unix/gsockunx.h:41: error: ‘class GSocket’ has a previous declaration as ‘class GSocket’
make: **\* [.objs.debug/BundleItemEditorCtrl.o] Error 1

**Comment by morgangrubb** [comment]
I have the same problem (Ubuntu 9.10 AMD64). A little googling has shown this is a fix http://trac.wxwidgets.org/changeset/61009 unfortunately it's already in external/patches/wxWidgets-gsock.patch and has already been applied to external/wxwidgets/src/gtk/gsockgtk.cpp.

I also tried this dirty hack mentioned here https://bugs.launchpad.net/ubuntu/+source/wxwidgets2.8/+bug/423845/comments/5 and that seemed to alleviate the pain when it got me to this issue http://github.com/etexteditor/e/issues/#issue/63. I applied the patch mentioned in there but the GSocket problem came back with a vengeance so this is no fix at all.

Currently not sure how to proceed to get this built.

**Comment by morgangrubb** [comment]
Noticed that I had external/wxwidgets/src/gtk1 as well as external/wxwidgets/src/gtk so I modified the gsockgtk.cpp file to undef GSocket but that hasn't worked either. Any suggestions?

**Comment by morgangrubb** [comment]
azuwis posted a fix for this one here: http://e-texteditor.com/forum/viewtopic.php?t=3511
