### ISSUE TITLE
Linker error in tm_syntaxhandler.cpp (Ubuntu 10.10 64bit)

### ISSUE THREAD

**Issue by mooware** [etexteditor/e#76]
I get a linker error when trying to build e:
    [LD] e
    .objs.release/tm_syntaxhandler.o: In function `TmSyntaxHandler::GetActions(wxString const&, std::deque<wxString const*, std::allocator<wxString const*> > const&) const':
    tm_syntaxhandler.cpp:(.text+0x5263): undefined reference to`Isalnum(wchar_t)'
    tm_syntaxhandler.cpp:(.text+0x5280): undefined reference to `Isalnum(wchar_t)'
    collect2: ld returned 1 exit status

I'd guess that the problem is that Isalnum(), defined in EditorCtrl.cpp, is inline. Because of this, it gets internal linkage, meaning that the linker will not see it.
The issue is probably caused by commit 1eeb6d3407e6b77a7250241f18faf791df6be910, in which uses of Isalnum() where moved to tm_syntaxhandler.cpp.
