### ISSUE TITLE
E will not compile on Ubuntu Lucid Lynx 10.04

### ISSUE THREAD

**Issue by robinduckett** [etexteditor/e#72]
Okay, I've been trying this for a while now. Caught offguard by bakefile requiring python2.3 from the get-packages-ubuntu.sh file, (it doesn't and works fine with python2.6 which is what lucid comes with).

So I finally got webkit compiling right, which is great, but now E won't compile.

```
[CC] BundleItemEditorCtrl.cpp
In file included from /usr/include/glib-2.0/gio/gio.h:28,
                 from /usr/include/gtk-2.0/gdk/gdkapplaunchcontext.h:30,
                 from /usr/include/gtk-2.0/gdk/gdk.h:32,
                 from /usr/include/gtk-2.0/gtk/gtk.h:32,
                 from key_hook.h:13,
                 from EditorCtrl.h:29,
                 from BundleItemEditorCtrl.h:4,
                 from BundleItemEditorCtrl.cpp:1:
/usr/include/glib-2.0/gio/giotypes.h:127: error: conflicting declaration 'typedef struct _GSocket GSocket'
/home/robin/e/external/out.debug/include/wx-2.8/wx/unix/gsockunx.h:41: error: 'class GSocket' has a previous declaration as 'class GSocket'
make: *** [.objs.debug/BundleItemEditorCtrl.o] Error 1
```

I have no idea what to do, is this an E bug or a wxwidgets bug?

**Comment by Tuxified** [comment]
It's really hard to build e as the necessary dependencies get updated all the time. Your situation includes a clash between wxWidgets/GTK and webkit. I've also tried to fix it manually, but it's not easy.

You could try one of the linux branches, this one seems to have a fix for Lynx: http://github.com/leeseon/e/tree/linux

**Comment by robinduckett** [comment]
No, not working.

The error (as you can see) is due to giotypes.h in glib2 bundled with lucid conflicting with the GSocket declaration in both the latest version of wxwidgets and the version required by E.

I believe this a wxwidgets error, to be honest.

**Comment by robinduckett** [comment]
giotypes.h section that's being conflicted with
    /**
     \* GSocket:
     *
     \* A lowlevel network socket object.
     *
     \* Since: 2.22
     **/
    typedef struct _GSocket                       GSocket;
---- gsocket.h ----
    #ifdef __WXWINCE__
    #include <stdlib.h>
    #endif

```
class GSocket;
```

**Comment by Tuxified** [comment]
Hi,

There's workaround for that problem: redefine gtk's GSocket. Patch e/src/key_hook.h:

```
#ifdef __WXGTK__
-  #include <gtk/gtk.h>
+#define GSocket GlibGSocket   
+#include <gtk/gtk.h>
+#undef GSocket
 //#include <gdk/gdkevents.h>
 //#include <gdk/gdkwindow.h>
 #endif
```

The easiest way (IMHO) to compile on Lucid is to use the linux branch:

git clone http://github.com/leeseon/e.git
cd e
git checkout origin/linux
--follow steps to compile from linux_notes.txt--

The linux branch contains specified versions of different dependencies, saves you the headache of fixing other conflicts ;)

**Comment by robinduckett** [comment]
Hmm, that worked :)

**Comment by silasrm** [comment]
I don't compiling your fork with sucess. it's crashed in momento open project or file for edit.
